#MineBot
#GPL and all that
# - espes

PLAYER_HEIGHT = 1.62

BLOCKS = set()
BLOCKS_NAMES = {}

#blocks
import bravo_blocks
for i, block in bravo_blocks.blocks.iteritems():
    if not isinstance(i, int):
        continue
    BLOCKS.add(i)
    BLOCKS_NAMES[i] = block.name
    varName = "BLOCK_"+block.name.replace("-", "").upper()
    globals()[varName] = i

BLOCKS = frozenset(BLOCKS)
BLOCKS_WALKABLE = frozenset([
    BLOCK_AIR,
    BLOCK_SAPLING,
    
    #BLOCK_WATER,
    #BLOCK_SPRING,
    
    #BLOCK_LAVA,
    #BLOCK_LAVASPRING,
    
    BLOCK_FLOWER,
    BLOCK_ROSE,
    BLOCK_BROWNMUSHROOM,
    BLOCK_REDMUSHROOM,
    BLOCK_TORCH,
    #BLOCK_FIRE,
    BLOCK_REDSTONEWIRE,
    BLOCK_SIGNPOST,
    BLOCK_WOODENDOOR,
    BLOCK_LADDER,
    BLOCK_TRACKS,
    BLOCK_WALLSIGN,
    BLOCK_STONEPLATE,
    BLOCK_IRONDOOR,
    BLOCK_WOODENPLATE,
    BLOCK_REDSTONETORCH,
    BLOCK_REDSTONETORCHON,
    BLOCK_ICE,
    BLOCK_PORTAL
])
BLOCKS_UNWALKABLE = BLOCKS ^ BLOCKS_WALKABLE

BLOCKS_UNBREAKABLE = frozenset([
    BLOCK_AIR,
    
    BLOCK_WATER,
    BLOCK_SPRING,
    
    BLOCK_LAVA,
    BLOCK_LAVASPRING,
    BLOCK_FIRE,
    BLOCK_BEDROCK,
    BLOCK_PORTAL
])
BLOCKS_BREAKABLE = BLOCKS ^ BLOCKS_UNBREAKABLE

BLOCKS_RESISTANCE = {
    BLOCK_STONE: 10,
    BLOCK_COBBLESTONE: 10,
    BLOCK_WOOD: 5,
    BLOCK_BEDROCK: 6000000,
    BLOCK_GOLDORE: 5,
    BLOCK_IRONORE: 5,
    BLOCK_COALORE: 5,
    BLOCK_GOLD: 10,
    BLOCK_IRON: 10,
    BLOCK_STEP: 10,
    BLOCK_DOUBLESTEP: 10,
    BLOCK_BRICK: 10,
    BLOCK_MOSSYCOBBLESTONE: 10,
    BLOCK_OBSIDIAN: 2000,
    BLOCK_DIAMONDORE: 5,
    BLOCK_DIAMOND: 10,
    BLOCK_REDSTONEORE: 5,
    BLOCK_GLOWINGREDSTONEORE: 5,
    BLOCK_JUKEBOX: 10,
    BLOCK_FENCE: 5
}

BLOCKS_HARDNESS = {
    BLOCK_STONE: 1.5,
    BLOCK_GRASS: 0.6,
    BLOCK_DIRT: 0.5,
    BLOCK_COBBLESTONE: 2.0,
    BLOCK_WOOD: 2.0,
    BLOCK_SAPLING: 0.0,
    BLOCK_BEDROCK: -1,
    BLOCK_SPRING: 100,
    BLOCK_WATER: 100,
    BLOCK_LAVASPRING: 0.0,
    BLOCK_LAVA: 100,
    BLOCK_SAND: 0.5,
    BLOCK_GRAVEL: 0.6,
    BLOCK_GOLDORE: 3,
    BLOCK_IRONORE: 3,
    BLOCK_COALORE: 3,
    BLOCK_LOG: 2.0,
    BLOCK_LEAVES: 0.2,
    BLOCK_SPONGE: 0.6,
    BLOCK_GLASS: 0.3,
    BLOCK_GREYCLOTH: 0.8,
    BLOCK_FLOWER: 0.0,
    BLOCK_ROSE: 0.0,
    BLOCK_BROWNMUSHROOM: 0.0,
    BLOCK_REDMUSHROOM: 0.0,
    BLOCK_GOLD: 3,
    BLOCK_IRON: 5,
    BLOCK_DOUBLESTEP: 2.0,
    BLOCK_STEP: 2.0,
    BLOCK_BRICK: 2.0,
    BLOCK_TNT: 0.0,
    BLOCK_BOOKSHELF: 1.5,
    BLOCK_MOSSYCOBBLESTONE: 2.0,
    BLOCK_OBSIDIAN: 10,
    BLOCK_TORCH: 0.0,
    BLOCK_FIRE: 0.0,
    BLOCK_MOBSPAWNER: 5,
    BLOCK_CHEST: 2.5,
    BLOCK_REDSTONEWIRE: 0.0,
    BLOCK_DIAMONDORE: 3,
    BLOCK_DIAMOND: 5,
    BLOCK_WORKBENCH: 2.5,
    BLOCK_CROPS: 0.0,
    BLOCK_SOIL: 0.6,
    BLOCK_FURNACE: 3.5,
    BLOCK_BURNINGFURNACE: 3.5,
    BLOCK_SIGNPOST: 1.0,
    BLOCK_WOODENDOOR: 3,
    BLOCK_LADDER: 0.4,
    BLOCK_TRACKS: 0.7,
    BLOCK_WALLSIGN: 1.0,
    BLOCK_LEVER: 0.5,
    BLOCK_STONEPLATE: 0.5,
    BLOCK_IRONDOOR: 5,
    BLOCK_WOODENPLATE: 0.5,
    BLOCK_REDSTONEORE: 3,
    BLOCK_GLOWINGREDSTONEORE: 3,
    BLOCK_REDSTONETORCH: 0.0,
    BLOCK_REDSTONETORCHON: 0.0,
    BLOCK_STONEBUTTON: 0.5,
    BLOCK_SNOW: 0.1,
    BLOCK_ICE: 0.5,
    BLOCK_SNOW: 0.2,
    BLOCK_CACTUS: 0.4,
    BLOCK_CLAY: 0.6,
    BLOCK_SUGARCANE: 0.0,
    BLOCK_JUKEBOX: 2.0,
    BLOCK_FENCE: 2.0,
    BLOCK_PUMPKIN: 1.0,
    BLOCK_BRIMSTONE: 0.4,
    BLOCK_SLOWSAND: 0.5,
    BLOCK_LIGHTSTONE: 0.3,
    BLOCK_PORTAL: -1,
    BLOCK_JACKOLANTERN: 1.0
}

ITEMS = set()
ITEMS_NAMES = {}

import bravo_blocks
for i, item in bravo_blocks.items.iteritems():
    if not isinstance(i, int):
        continue
    ITEMS.add(i)
    ITEMS_NAMES[i] = item.name
    varName = "ITEM_"+item.name.replace("-", "").upper()
    globals()[varName] = i

ITEMS_TOOLLEVEL = {
    ITEM_WOODENSWORD: 0,
    ITEM_WOODENSHOVEL: 0,
    ITEM_WOODENPICKAXE: 0,
    ITEM_WOODENAXE: 0,
    ITEM_WOODENHOE: 0,
    
    ITEM_GOLDSWORD: 0,
    ITEM_GOLDSHOVEL: 0,
    ITEM_GOLDPICKAXE: 0,
    ITEM_GOLDAXE: 0,
    ITEM_GOLDHOE: 0,
    
    ITEM_STONESWORD: 1,
    ITEM_STONESHOVEL: 1,
    ITEM_STONEPICKAXE: 1,
    ITEM_STONEAXE: 1,
    ITEM_STONEHOE: 1,
    
    ITEM_IRONSWORD: 2,
    ITEM_IRONSHOVEL: 2,
    ITEM_IRONPICKAXE: 2,
    ITEM_IRONAXE: 2,
    ITEM_IRONHOE: 2,
    
    ITEM_DIAMONDSWORD: 3,
    ITEM_DIAMONDSHOVEL: 3,
    ITEM_DIAMONDPICKAXE: 3,
    ITEM_DIAMONDAXE: 3,
    ITEM_DIAMONDHOE: 3
}

ITEMS_TOOLUSES = {
    ITEM_WOODENSWORD: 59,
    ITEM_WOODENSHOVEL: 59,
    ITEM_WOODENPICKAXE: 59,
    ITEM_WOODENAXE: 59,
    ITEM_WOODENHOE: 59,

    ITEM_GOLDSWORD: 32,
    ITEM_GOLDSHOVEL: 32,
    ITEM_GOLDPICKAXE: 32,
    ITEM_GOLDAXE: 32,
    ITEM_GOLDHOE: 32,

    ITEM_STONESWORD: 131,
    ITEM_STONESHOVEL: 131,
    ITEM_STONEPICKAXE: 131,
    ITEM_STONEAXE: 131,
    ITEM_STONEHOE: 131,

    ITEM_IRONSWORD: 250,
    ITEM_IRONSHOVEL: 250,
    ITEM_IRONPICKAXE: 250,
    ITEM_IRONAXE: 250,
    ITEM_IRONHOE: 250,

    ITEM_DIAMONDSWORD: 1561,
    ITEM_DIAMONDSHOVEL: 1561,
    ITEM_DIAMONDPICKAXE: 1561,
    ITEM_DIAMONDAXE: 1561,
    ITEM_DIAMONDHOE: 1561
}

ITEMS_TOOLEFFICIENCY = {
    ITEM_WOODENSWORD: 2,
    ITEM_WOODENSHOVEL: 2,
    ITEM_WOODENPICKAXE: 2,
    ITEM_WOODENAXE: 2,
    ITEM_WOODENHOE: 2,

    ITEM_GOLDSWORD: 12,
    ITEM_GOLDSHOVEL: 12,
    ITEM_GOLDPICKAXE: 12,
    ITEM_GOLDAXE: 12,
    ITEM_GOLDHOE: 12,

    ITEM_STONESWORD: 4,
    ITEM_STONESHOVEL: 4,
    ITEM_STONEPICKAXE: 4,
    ITEM_STONEAXE: 4,
    ITEM_STONEHOE: 4,

    ITEM_IRONSWORD: 6,
    ITEM_IRONSHOVEL: 6,
    ITEM_IRONPICKAXE: 6,
    ITEM_IRONAXE: 6,
    ITEM_IRONHOE: 6,

    ITEM_DIAMONDSWORD: 8,
    ITEM_DIAMONDSHOVEL: 8,
    ITEM_DIAMONDPICKAXE: 8,
    ITEM_DIAMONDAXE: 8,
    ITEM_DIAMONDHOE: 8
}

ITEMS_TOOLS = frozenset(ITEMS_TOOLLEVEL.iterkeys())

ITEMS_SWORD = frozenset([
    ITEM_WOODENSWORD,
    ITEM_GOLDSWORD,
    ITEM_STONESWORD,
    ITEM_IRONSWORD,
    ITEM_DIAMONDSWORD
])

ITEMS_SHOVEL = frozenset([
    ITEM_WOODENSHOVEL,
    ITEM_GOLDSHOVEL,
    ITEM_STONESHOVEL,
    ITEM_IRONSHOVEL,
    ITEM_DIAMONDSHOVEL
])

ITEMS_PICKAXE = frozenset([
    ITEM_WOODENPICKAXE,
    ITEM_GOLDPICKAXE,
    ITEM_STONEPICKAXE,
    ITEM_IRONPICKAXE,
    ITEM_DIAMONDPICKAXE
])

ITEMS_AXE = frozenset([
    ITEM_WOODENAXE,
    ITEM_GOLDAXE,
    ITEM_STONEAXE,
    ITEM_IRONAXE,
    ITEM_DIAMONDAXE
])

BLOCKITEM_NAMES = dict(BLOCKS_NAMES.items()+ITEMS_NAMES.items())
BLOCKITEM_LOOKUP = dict((value, name) for name, value in BLOCKITEM_NAMES.iteritems())

ITEMS_UNSTACKABLE = ITEMS_TOOLS | frozenset([
    ITEM_FLINTANDSTEEL,
    ITEM_APPLE,
    ITEM_BOW,
    ITEM_BOWL,
    ITEM_BREAD,
    ITEM_LEATHERHELMET,
    ITEM_LEATHERCHESTPLATE,
    ITEM_LEATHERLEGGINGS,
    ITEM_LEATHERBOOTS,
    ITEM_CHAINMAILHELMET,
    ITEM_CHAINMAILCHESTPLATE,
    ITEM_CHAINMAILLEGGINGS,
    ITEM_CHAINMAILBOOTS,
    ITEM_IRONHELMET,
    ITEM_IRONCHESTPLATE,
    ITEM_IRONLEGGINGS,
    ITEM_IRONBOOTS,
    ITEM_DIAMONDHELMET,
    ITEM_DIAMONDCHESTPLATE,
    ITEM_DIAMONDLEGGINGS,
    ITEM_DIAMONDBOOTS,
    ITEM_GOLDHELMET,
    ITEM_GOLDCHESTPLATE,
    ITEM_GOLDLEGGINGS,
    ITEM_GOLDBOOTS,
    ITEM_FLINT,
    ITEM_RAWPORKCHOP,
    ITEM_COOKEDPORKCHOP,
    ITEM_GOLDENAPPLE,
    ITEM_SIGN,
    ITEM_WOODENDOOR,
    ITEM_BUCKET,
    ITEM_WATERBUCKET,
    ITEM_LAVABUCKET,
    ITEM_MINECART,
    ITEM_SADDLE,
    ITEM_IRONDOOR,
    ITEM_BOAT,
    ITEM_MILK,
    ITEM_STORAGEMINECART,
    ITEM_POWEREDMINECART,
    ITEM_RAWFISH,
    ITEM_COOKEDFISH,
    ITEM_CAKE,
    ITEM_GOLDMUSICDISC,
    ITEM_GREENMUSICDISC
])

ITEMS_SPECIALSTACKS = {
    ITEM_SNOWBALL: 16,
    ITEM_EGG: 16
}

OBJECT_BOAT = 1
OBJECT_MINECART = 10
OBJECT_STORAGECART = 11
OBJECT_POWEREDCART = 12
OBJECT_ACTIVATEDTNT = 50
OBJECT_ARROW = 60
OBJECT_THROWNSNOWBALL = 61
OBJECT_THROWNEGG = 62
OBJECT_FALLINGSAND = 70
OBJECT_FALLINGGRAVEL = 71
OBJECT_FISHINGFLOAT = 90

INVENTORYTYPE_CHEST = 0
INVENTORYTYPE_WORKBENCH = 1
INVENTORYTYPE_FURNACE = 2



MATERIAL_IRON = 0
MATERIAL_PUMPKIN = 1
MATERIAL_LAVA = 2
MATERIAL_DIRT = 3
MATERIAL_SPONGE = 4
MATERIAL_WOOD = 5
MATERIAL_WOOL = 6
MATERIAL_FIRE = 7
MATERIAL_STONE = 9
MATERIAL_GOLD = 10
MATERIAL_ICE = 11
MATERIAL_WATER = 12
MATERIAL_PORTAL = 13
MATERIAL_SAND = 14
MATERIAL_CACTUS = 15
MATERIAL_DIAMONDd = 16
MATERIAL_SNOWBlock = 17
MATERIAL_CLAY = 18
MATERIAL_LEAVES = 19
MATERIAL_TNT = 20
MATERIAL_CAKE = 21
MATERIAL_CROPS = 22
MATERIAL_SNOW = 23
MATERIAL_REDSTONE = 24
MATERIAL_GLASS = 25

BLOCKITEM_MATERIAL = {
    0x00: None,
    0x01: MATERIAL_STONE,
    0x02: MATERIAL_DIRT,
    0x03: MATERIAL_DIRT,
    0x04: MATERIAL_STONE,
    0x05: MATERIAL_WOOD,
    0x06: MATERIAL_CROPS,
    0x07: MATERIAL_STONE,
    0x08: MATERIAL_WATER,
    0x09: MATERIAL_WATER,
    0x0A: MATERIAL_LAVA,
    0x0B: MATERIAL_LAVA,
    0x0C: MATERIAL_SAND,
    0x0D: MATERIAL_SAND,
    0x0E: MATERIAL_STONE,
    0x0F: MATERIAL_STONE,
    0x10: MATERIAL_STONE,
    0x11: MATERIAL_WOOD,
    0x12: MATERIAL_LEAVES,
    0x13: MATERIAL_SPONGE,
    0x14: MATERIAL_GLASS,
    0x15: MATERIAL_STONE,
    0x16: MATERIAL_STONE,
    0x17: MATERIAL_STONE,
    0x18: MATERIAL_STONE,
    0x19: MATERIAL_WOOD,
    0x1A: MATERIAL_WOOL,
    0x23: MATERIAL_WOOL,
    0x25: MATERIAL_CROPS,
    0x26: MATERIAL_CROPS,
    0x27: MATERIAL_CROPS,
    0x28: MATERIAL_CROPS,
    0x29: MATERIAL_IRON,
    0x2A: MATERIAL_IRON,
    0x2B: MATERIAL_STONE,
    0x2C: MATERIAL_STONE,
    0x2D: MATERIAL_STONE,
    0x2E: MATERIAL_TNT,
    0x2F: MATERIAL_WOOD,
    0x30: MATERIAL_STONE,
    0x31: MATERIAL_STONE,
    0x32: MATERIAL_REDSTONE,
    0x33: MATERIAL_FIRE,
    0x34: MATERIAL_STONE,
    0x35: MATERIAL_WOOD,
    0x36: MATERIAL_WOOD,
    0x37: MATERIAL_REDSTONE,
    0x38: MATERIAL_STONE,
    0x39: MATERIAL_IRON,
    0x3A: MATERIAL_WOOD,
    0x3B: MATERIAL_CROPS,
    0x3C: MATERIAL_DIRT,
    0x3D: MATERIAL_STONE,
    0x3E: MATERIAL_STONE,
    0x3F: MATERIAL_WOOD,
    0x40: MATERIAL_WOOD,
    0x41: MATERIAL_REDSTONE,
    0x42: MATERIAL_REDSTONE,
    0x43: MATERIAL_STONE,
    0x44: MATERIAL_WOOD,
    0x45: MATERIAL_REDSTONE,
    0x46: MATERIAL_STONE,
    0x47: MATERIAL_IRON,
    0x48: MATERIAL_WOOD,
    0x49: MATERIAL_STONE,
    0x4A: MATERIAL_STONE,
    0x4B: MATERIAL_REDSTONE,
    0x4C: MATERIAL_REDSTONE,
    0x4D: MATERIAL_REDSTONE,
    0x4E: MATERIAL_SNOW,
    0x4F: MATERIAL_ICE,
    0x50: MATERIAL_SNOWBlock,
    0x51: MATERIAL_CACTUS,
    0x52: MATERIAL_CLAY,
    0x53: MATERIAL_CROPS,
    0x54: MATERIAL_WOOD,
    0x55: MATERIAL_WOOD,
    0x56: MATERIAL_PUMPKIN,
    0x57: MATERIAL_STONE,
    0x58: MATERIAL_SAND,
    0x59: MATERIAL_GLASS,
    0x5A: MATERIAL_PORTAL,
    0x5B: MATERIAL_PUMPKIN,
    0x5C: MATERIAL_CAKE,
    0x5D: MATERIAL_REDSTONE,
    0x5E: MATERIAL_REDSTONE,
    0x100: MATERIAL_IRON,
    0x101: MATERIAL_IRON,
    0x102: MATERIAL_IRON,
    0x103: None,
    0x104: None,
    0x105: None,
    0x106: None,
    0x107: None,
    0x108: None,
    0x109: None,
    0x10A: None,
    0x10B: MATERIAL_IRON,
    0x10C: MATERIAL_WOOD,
    0x10D: MATERIAL_WOOD,
    0x10E: MATERIAL_WOOD,
    0x10F: MATERIAL_WOOD,
    0x110: MATERIAL_STONE,
    0x111: MATERIAL_STONE,
    0x112: MATERIAL_STONE,
    0x113: MATERIAL_STONE,
    0x114: MATERIAL_DIAMONDd,
    0x115: MATERIAL_DIAMONDd,
    0x116: MATERIAL_DIAMONDd,
    0x117: MATERIAL_DIAMONDd,
    0x118: None,
    0x119: None,
    0x11A: None,
    0x11B: MATERIAL_GOLD,
    0x11C: MATERIAL_GOLD,
    0x11D: MATERIAL_GOLD,
    0x11E: MATERIAL_GOLD,
    0x11F: None,
    0x120: None,
    0x121: None,
    0x122: MATERIAL_WOOD,
    0x123: MATERIAL_STONE,
    0x124: MATERIAL_IRON,
    0x125: MATERIAL_DIAMONDd,
    0x126: MATERIAL_GOLD,
    0x127: None,
    0x128: None,
    0x129: None,
    0x12A: None,
    0x12B: None,
    0x12C: None,
    0x12D: None,
    0x12E: None,
    0x12F: None,
    0x130: None,
    0x131: None,
    0x132: None,
    0x133: None,
    0x134: None,
    0x135: None,
    0x136: None,
    0x137: None,
    0x138: None,
    0x139: None,
    0x13A: None,
    0x13B: None,
    0x13C: None,
    0x13D: None,
    0x13E: None,
    0x13F: None,
    0x140: None,
    0x141: None,
    0x142: None,
    0x143: None,
    0x144: None,
    0x145: None,
    0x146: None,
    0x147: None,
    0x148: None,
    0x149: None,
    0x14A: None,
    0x14B: None,
    0x14C: None,
    0x14D: None,
    0x14E: None,
    0x14F: None,
    0x150: None,
    0x151: None,
    0x152: None,
    0x153: None,
    0x154: None,
    0x155: None,
    0x156: None,
    0x157: None,
    0x158: None,
    0x159: None,
    0x15A: None,
    0x15B: None,
    0x15C: None,
    0x15D: None,
    0x15E: None,
    0x15F: None,
    0x160: None,
    0x161: None,
    0x162: None,
    0x163: None,
    0x164: None,
    0x8D0: None,
    0x8D1: None
}

