#MineBot
#GPL and all that
# - espes


import os
from format import *


#network packets
TYPE_KEEPALIVE = 0x00
TYPE_LOGIN = 0x01
TYPE_HANDSHAKE = 0x02
TYPE_CHAT = 0x03
TYPE_UPDATETIME = 0x04
TYPE_ENTITYEQUIPMENT = 0x05
TYPE_SPAWNPOSITION = 0x06
TYPE_USEENTITY = 0x07
TYPE_PLAYERHEALTH = 0x08
TYPE_RESPAWN = 0x09
TYPE_PLAYERONGROUND = 0x0A
TYPE_PLAYERPOSITION = 0x0B
TYPE_PLAYERLOOK = 0x0C
TYPE_PLAYERPOSITIONLOOK = 0x0D
TYPE_PLAYERBLOCKDIG = 0x0E
TYPE_PLAYERBLOCKPLACE = 0x0F
TYPE_ITEMSWITCH = 0x10
TYPE_ADDINVENTORY = 0x11
TYPE_ARMANIMATION = 0x12
TYPE_ENTITYACTION = 0x13
TYPE_NAMEDENTITYSPAWN = 0x14
TYPE_PICKUPSPAWN = 0x15
TYPE_COLLECTITEM = 0x16
TYPE_ADDOBJECT = 0x17
TYPE_MOBSPAWN = 0x18
TYPE_ENTITYPAINTING = 0x19
TYPE_ENTITYVELOCITY = 0x1C
TYPE_DESTROYENTITY = 0x1D
TYPE_ENTITY = 0x1E
TYPE_ENTITYMOVE = 0x1F
TYPE_ENTITYLOOK = 0x20
TYPE_ENTITYMOVELOOK = 0x21
TYPE_ENTITYTELEPORT = 0x22
TYPE_ENTITYSTATUS = 0x26
TYPE_ATTACHENTITY = 0x27
TYPE_ENTITYMETADATA = 0x28
TYPE_PRECHUNK = 0x32
TYPE_CHUNK = 0x33
TYPE_MULTIBLOCKCHANGE = 0x34
TYPE_BLOCKCHANGE = 0x35
TYPE_PLAYNOTEBLOCK = 0x36
TYPE_COMPLEXENTITY = 0x3B
TYPE_EXPLOSION = 0x3C
TYPE_WINDOWOPEN = 0x64
TYPE_WINDOWCLOSE = 0x65
TYPE_WINDOWCLICK = 0x66
TYPE_SETSLOT = 0x67
TYPE_WINDOWITEMS = 0x68
TYPE_TRANSACTION = 0x6A
TYPE_UPDATESIGN = 0x82
TYPE_DISCONNECT = 0xFF
        

TYPE_FORMATS = {
	TYPE_KEEPALIVE: Format(""),
	TYPE_LOGIN: Format("iSSqb"),
	TYPE_HANDSHAKE: Format("S"),
	TYPE_CHAT: Format("S"),
	TYPE_UPDATETIME: Format("q"),
	TYPE_ENTITYEQUIPMENT: Format("ihhh"),
	TYPE_SPAWNPOSITION: Format("iii"),
	TYPE_USEENTITY: Format("iib"),
	TYPE_PLAYERHEALTH: Format("h"),
	TYPE_RESPAWN: Format(""),
	TYPE_PLAYERONGROUND: Format("b"),
	TYPE_PLAYERPOSITION: Format("ddddb"),
	TYPE_PLAYERLOOK: Format("ffb"),
	TYPE_PLAYERPOSITIONLOOK: Format("ddddffb"),
	TYPE_PLAYERBLOCKDIG: Format("bibib"),
	TYPE_PLAYERBLOCKPLACE: BlockPlaceFormat(),
	TYPE_ITEMSWITCH: Format("h"),
	TYPE_ADDINVENTORY: Format("hbh"),
	TYPE_ARMANIMATION: Format("ib"),
	TYPE_ENTITYACTION: Format("ib"),
	TYPE_NAMEDENTITYSPAWN: Format("iSiiibbh"),
	TYPE_PICKUPSPAWN: Format("ihbhiiibbb"),
	TYPE_COLLECTITEM: Format("ii"),
	TYPE_ADDOBJECT: Format("ibiii"),
	TYPE_MOBSPAWN: Format("ibiiibbM"),
	TYPE_ENTITYPAINTING: Format("iSiiii"),
	TYPE_ENTITYVELOCITY: Format("ihhh"),
	TYPE_DESTROYENTITY: Format("i"),
	TYPE_ENTITY: Format("i"),
	TYPE_ENTITYMOVE: Format("ibbb"),
	TYPE_ENTITYLOOK: Format("ibb"),
	TYPE_ENTITYMOVELOOK: Format("ibbbbb"),
	TYPE_ENTITYTELEPORT: Format("iiiibb"),
	TYPE_ENTITYSTATUS: Format("ib"),
	TYPE_ATTACHENTITY: Format("ii"),
	TYPE_ENTITYMETADATA: Format("iM"),
	TYPE_PRECHUNK: Format("iib"),
	TYPE_CHUNK: ChunkFormat(),
	TYPE_MULTIBLOCKCHANGE: MultiBlockChangeFormat(),
	TYPE_BLOCKCHANGE: Format("ibibb"),
	TYPE_PLAYNOTEBLOCK: Format("ihibb"),
	TYPE_COMPLEXENTITY: Format("ihiS"),
	TYPE_WINDOWOPEN: Format("bbSb"),
	TYPE_WINDOWCLOSE: Format("b"),
	TYPE_WINDOWCLICK: WindowClickFormat(),
	TYPE_WINDOWITEMS: WindowItemsFormat(),
	TYPE_TRANSACTION: Format("bhb"),
	TYPE_EXPLOSION: ExplosionFormat(),
	TYPE_SETSLOT: SetSlotFormat(),
	TYPE_UPDATESIGN: Format("ihiSSSS"),
	TYPE_DISCONNECT: Format("S")
}


BLOCKS = set()
#blocks
from pymclevel import materials, items
import re
for id, name in enumerate(materials.names):
    if name == 'Future Block!':
        continue
    varName = "BLOCK_"+re.sub(r"[\s\(\)]|(?:/.*)", "", name).upper()
    globals()[varName] = id
    BLOCKS.add(id)

BLOCKS = frozenset(BLOCKS)

BLOCKS_WALKABLE = frozenset([
    BLOCK_AIR,
    BLOCK_SAPLING,
    
    #BLOCK_WATER,
    #BLOCK_STATIONARYWATER,
    
    #BLOCK_LAVA,
    #BLOCK_STATIONARYLAVA,
    
    BLOCK_FLOWER,
    BLOCK_ROSE,
    BLOCK_BROWNMUSHROOM,
    BLOCK_REDMUSHROOM,
    BLOCK_TORCH,
    #BLOCK_FIRE,
    BLOCK_REDSTONEWIRE,
    BLOCK_SIGN,
    BLOCK_WOODENDOOR,
    BLOCK_LADDER,
    BLOCK_RAIL,
    BLOCK_WALLSIGN,
    BLOCK_STONEFLOORPLATE,
    BLOCK_IRONDOOR,
    BLOCK_WOODFLOORPLATE,
    BLOCK_REDSTONETORCHOFF,
    BLOCK_REDSTONETORCHON,
    BLOCK_ICE,
    BLOCK_NETHERPORTAL
])

BLOCKS_UNBREAKABLE = frozenset([
    BLOCK_AIR,
    
    BLOCK_WATER,
    BLOCK_STATIONARYWATER,
    
    BLOCK_LAVA,
    BLOCK_STATIONARYLAVA,
    BLOCK_FIRE,
    BLOCK_BEDROCK,
    BLOCK_NETHERPORTAL
])
BLOCKS_BREAKABLE = BLOCKS ^ BLOCKS_UNBREAKABLE

BLOCKS_RESISTANCE = {
    BLOCK_STONE: 10,
    BLOCK_COBBLESTONE: 10,
    BLOCK_WOOD: 5,
    BLOCK_BEDROCK: 6000000,
    BLOCK_GOLDORE: 5,
    BLOCK_IRONORE: 5,
    BLOCK_COALORE: 5,
    BLOCK_SOLIDGOLDBLOCK: 10,
    BLOCK_SOLIDIRONBLOCK: 10,
    BLOCK_SINGLESTONESTAIRHALFSTEP: 10,
    BLOCK_DOUBLESTONESTAIRSTEP: 10,
    BLOCK_REDBRICKTILE: 10,
    BLOCK_MOSSCOVEREDCOBBLESTONE: 10,
    BLOCK_OBSIDIAN: 2000,
    BLOCK_DIAMONDORE: 5,
    BLOCK_SOLIDDIAMONDBLOCK: 10,
    BLOCK_REDSTONEORE: 5,
    BLOCK_REDSTONEOREGLOWING: 5,
    BLOCK_JUKEBOX: 10,
    BLOCK_FENCE: 5
}

BLOCKS_HARDNESS = {
    BLOCK_STONE: 1.5,
    BLOCK_GRASS: 0.6,
    BLOCK_DIRT: 0.5,
    BLOCK_COBBLESTONE: 2.0,
    BLOCK_WOOD: 2.0,
    BLOCK_SAPLING: 0.0,
    BLOCK_BEDROCK: -1,
    BLOCK_STATIONARYWATER: 100,
    BLOCK_WATER: 100,
    BLOCK_STATIONARYLAVA: 0.0,
    BLOCK_LAVA: 100,
    BLOCK_SAND: 0.5,
    BLOCK_GRAVEL: 0.6,
    BLOCK_GOLDORE: 3,
    BLOCK_IRONORE: 3,
    BLOCK_COALORE: 3,
    BLOCK_TREETRUNK: 2.0,
    BLOCK_LEAVES: 0.2,
    BLOCK_SPONGE: 0.6,
    BLOCK_GLASS: 0.3,
    BLOCK_WHITEWOOLCLOTH: 0.8,
    BLOCK_FLOWER: 0.0,
    BLOCK_ROSE: 0.0,
    BLOCK_BROWNMUSHROOM: 0.0,
    BLOCK_REDMUSHROOM: 0.0,
    BLOCK_SOLIDGOLDBLOCK: 3,
    BLOCK_SOLIDIRONBLOCK: 5,
    BLOCK_DOUBLESTONESTAIRSTEP: 2.0,
    BLOCK_SINGLESTONESTAIRHALFSTEP: 2.0,
    BLOCK_REDBRICKTILE: 2.0,
    BLOCK_TNT: 0.0,
    BLOCK_BOOKSHELF: 1.5,
    BLOCK_MOSSCOVEREDCOBBLESTONE: 2.0,
    BLOCK_OBSIDIAN: 10,
    BLOCK_TORCH: 0.0,
    BLOCK_FIRE: 0.0,
    BLOCK_MOBSPAWNER: 5,
    BLOCK_CHEST: 2.5,
    BLOCK_REDSTONEWIRE: 0.0,
    BLOCK_DIAMONDORE: 3,
    BLOCK_SOLIDDIAMONDBLOCK: 5,
    BLOCK_CRAFTINGTABLE: 2.5,
    BLOCK_CROPS: 0.0,
    BLOCK_FARMLAND: 0.6,
    BLOCK_FURNACE: 3.5,
    BLOCK_LITFURNACE: 3.5,
    BLOCK_SIGN: 1.0,
    BLOCK_WOODENDOOR: 3,
    BLOCK_LADDER: 0.4,
    BLOCK_RAIL: 0.7,
    BLOCK_WALLSIGN: 1.0,
    BLOCK_LEVER: 0.5,
    BLOCK_STONEFLOORPLATE: 0.5,
    BLOCK_IRONDOOR: 5,
    BLOCK_WOODFLOORPLATE: 0.5,
    BLOCK_REDSTONEORE: 3,
    BLOCK_REDSTONEOREGLOWING: 3,
    BLOCK_REDSTONETORCHOFF: 0.0,
    BLOCK_REDSTONETORCHON: 0.0,
    BLOCK_STONEBUTTON: 0.5,
    BLOCK_SNOW: 0.1,
    BLOCK_ICE: 0.5,
    BLOCK_SNOW: 0.2,
    BLOCK_CACTUS: 0.4,
    BLOCK_CLAY: 0.6,
    BLOCK_REEDS: 0.0,
    BLOCK_JUKEBOX: 2.0,
    BLOCK_FENCE: 2.0,
    BLOCK_PUMPKIN: 1.0,
    BLOCK_BLOODSTONE: 0.4,
    BLOCK_SLOWSAND: 0.5,
    BLOCK_LIGHTSTONE: 0.3,
    BLOCK_NETHERPORTAL: -1,
    BLOCK_GLOWINGPUMPKIN: 1.0
}

MATERIAL_ROCK = frozenset([
    BLOCK_COBBLESTONE,
    BLOCK_BEDROCK,
    BLOCK_REDBRICKTILE,
    BLOCK_MOSSCOVEREDCOBBLESTONE,
    BLOCK_REDSTONEORE,
    BLOCK_REDSTONEOREGLOWING,
    BLOCK_WOODFLOORPLATE,
    BLOCK_STONEFLOORPLATE,
    BLOCK_STONEBUTTON
])

MATERIAL_IRON = frozenset([
    BLOCK_IRONDOOR,
    BLOCK_GOLDORE,
    BLOCK_IRONORE,
    BLOCK_SOLIDIRONBLOCK,
    BLOCK_SOLIDDIAMONDBLOCK,
])

#items
for name, id in items.items.names.iteritems():
    varName = "ITEM_"+re.sub(r"[\s\(\)]", "", name).upper()
    globals()[varName] = id


ITEMS_TOOLLEVEL = {
    ITEM_WOODSWORD: 0,
    ITEM_WOODSHOVEL: 0,
    ITEM_WOODPICKAXE: 0,
    ITEM_WOODAXE: 0,
    ITEM_WOODHOE: 0,
    
    ITEM_GOLDSWORD: 0,
    ITEM_GOLDSHOVEL: 0,
    ITEM_GOLDPICKAXE: 0,
    ITEM_GOLDAXE: 0,
    ITEM_GOLDHOE: 0,
    
    ITEM_STONESWORD: 1,
    ITEM_STONESHOVEL: 1,
    ITEM_STONEPICKAXE: 1,
    ITEM_STONEAXE: 1,
    ITEM_STONEHOE: 1,
    
    ITEM_IRONSWORD: 2,
    ITEM_IRONSHOVEL: 2,
    ITEM_IRONPICKAXE: 2,
    ITEM_IRONAXE: 2,
    ITEM_IRONHOE: 2,
    
    ITEM_DIAMONDSWORD: 3,
    ITEM_DIAMONDSHOVEL: 3,
    ITEM_DIAMONDPICKAXE: 3,
    ITEM_DIAMONDAXE: 3,
    ITEM_DIAMONDHOE: 3
}

ITEMS_TOOLS = frozenset(ITEMS_TOOLLEVEL.iterkeys())

ITEMS_SWORD = frozenset([
    ITEM_WOODSWORD,
    ITEM_GOLDSWORD,
    ITEM_STONESWORD,
    ITEM_IRONSWORD,
    ITEM_DIAMONDSWORD
])

ITEMS_SHOVEL = frozenset([
    ITEM_WOODSHOVEL,
    ITEM_GOLDSHOVEL,
    ITEM_STONESHOVEL,
    ITEM_IRONSHOVEL,
    ITEM_DIAMONDSHOVEL
])

ITEMS_PICKAXE = frozenset([
    ITEM_WOODPICKAXE,
    ITEM_GOLDPICKAXE,
    ITEM_STONEPICKAXE,
    ITEM_IRONPICKAXE,
    ITEM_DIAMONDPICKAXE
])

ITEMS_AXE = frozenset([
    ITEM_WOODAXE,
    ITEM_GOLDAXE,
    ITEM_STONEAXE,
    ITEM_IRONAXE,
    ITEM_DIAMONDAXE
])


OBJECT_BOAT = 1
OBJECT_MINECART = 10
OBJECT_STORAGECART = 11
OBJECT_POWEREDCART = 12
OBJECT_ACTIVATEDTNT = 50
OBJECT_ARROW = 60
OBJECT_THROWNSNOWBALL = 61
OBJECT_THROWNEGG = 62
OBJECT_FALLINGSAND = 70
OBJECT_FALLINGGRAVEL = 71
OBJECT_FISHINGFLOAT = 90

INVENTORYTYPE_CHEST = 0
INVENTORYTYPE_WORKBENCH = 1
INVENTORYTYPE_FURNACE = 2