#MineBot
#GPL and all that
# - espes

PLAYER_HEIGHT = 1.62

BLOCKS = set()
BLOCKS_NAMES = {}

#blocks
from pymclevel import materials, items
import re
for id, name in enumerate(materials.names):
    if name == 'Future Block!':
        continue
    varName = "BLOCK_"+re.sub(r"[\s\(\)]|(?:/.*)", "", name).upper()
    globals()[varName] = id
    BLOCKS.add(id)
    BLOCKS_NAMES[id] = name

BLOCKS = frozenset(BLOCKS)

BLOCKS_WALKABLE = frozenset([
    BLOCK_AIR,
    BLOCK_SAPLING,
    
    #BLOCK_WATER,
    #BLOCK_STATIONARYWATER,
    
    #BLOCK_LAVA,
    #BLOCK_STATIONARYLAVA,
    
    BLOCK_FLOWER,
    BLOCK_ROSE,
    BLOCK_BROWNMUSHROOM,
    BLOCK_REDMUSHROOM,
    BLOCK_TORCH,
    #BLOCK_FIRE,
    BLOCK_REDSTONEWIRE,
    BLOCK_SIGN,
    BLOCK_WOODENDOOR,
    BLOCK_LADDER,
    BLOCK_RAIL,
    BLOCK_WALLSIGN,
    BLOCK_STONEFLOORPLATE,
    BLOCK_IRONDOOR,
    BLOCK_WOODFLOORPLATE,
    BLOCK_REDSTONETORCHOFF,
    BLOCK_REDSTONETORCHON,
    BLOCK_ICE,
    BLOCK_NETHERPORTAL
])

BLOCKS_UNBREAKABLE = frozenset([
    BLOCK_AIR,
    
    BLOCK_WATER,
    BLOCK_STATIONARYWATER,
    
    BLOCK_LAVA,
    BLOCK_STATIONARYLAVA,
    BLOCK_FIRE,
    BLOCK_BEDROCK,
    BLOCK_NETHERPORTAL
])
BLOCKS_BREAKABLE = BLOCKS ^ BLOCKS_UNBREAKABLE

BLOCKS_RESISTANCE = {
    BLOCK_STONE: 10,
    BLOCK_COBBLESTONE: 10,
    BLOCK_WOOD: 5,
    BLOCK_BEDROCK: 6000000,
    BLOCK_GOLDORE: 5,
    BLOCK_IRONORE: 5,
    BLOCK_COALORE: 5,
    BLOCK_SOLIDGOLDBLOCK: 10,
    BLOCK_SOLIDIRONBLOCK: 10,
    BLOCK_SINGLESTONESTAIRHALFSTEP: 10,
    BLOCK_DOUBLESTONESTAIRSTEP: 10,
    BLOCK_REDBRICKTILE: 10,
    BLOCK_MOSSCOVEREDCOBBLESTONE: 10,
    BLOCK_OBSIDIAN: 2000,
    BLOCK_DIAMONDORE: 5,
    BLOCK_SOLIDDIAMONDBLOCK: 10,
    BLOCK_REDSTONEORE: 5,
    BLOCK_REDSTONEOREGLOWING: 5,
    BLOCK_JUKEBOX: 10,
    BLOCK_FENCE: 5
}

BLOCKS_HARDNESS = {
    BLOCK_STONE: 1.5,
    BLOCK_GRASS: 0.6,
    BLOCK_DIRT: 0.5,
    BLOCK_COBBLESTONE: 2.0,
    BLOCK_WOOD: 2.0,
    BLOCK_SAPLING: 0.0,
    BLOCK_BEDROCK: -1,
    BLOCK_STATIONARYWATER: 100,
    BLOCK_WATER: 100,
    BLOCK_STATIONARYLAVA: 0.0,
    BLOCK_LAVA: 100,
    BLOCK_SAND: 0.5,
    BLOCK_GRAVEL: 0.6,
    BLOCK_GOLDORE: 3,
    BLOCK_IRONORE: 3,
    BLOCK_COALORE: 3,
    BLOCK_TREETRUNK: 2.0,
    BLOCK_LEAVES: 0.2,
    BLOCK_SPONGE: 0.6,
    BLOCK_GLASS: 0.3,
    BLOCK_WHITEWOOLCLOTH: 0.8,
    BLOCK_FLOWER: 0.0,
    BLOCK_ROSE: 0.0,
    BLOCK_BROWNMUSHROOM: 0.0,
    BLOCK_REDMUSHROOM: 0.0,
    BLOCK_SOLIDGOLDBLOCK: 3,
    BLOCK_SOLIDIRONBLOCK: 5,
    BLOCK_DOUBLESTONESTAIRSTEP: 2.0,
    BLOCK_SINGLESTONESTAIRHALFSTEP: 2.0,
    BLOCK_REDBRICKTILE: 2.0,
    BLOCK_TNT: 0.0,
    BLOCK_BOOKSHELF: 1.5,
    BLOCK_MOSSCOVEREDCOBBLESTONE: 2.0,
    BLOCK_OBSIDIAN: 10,
    BLOCK_TORCH: 0.0,
    BLOCK_FIRE: 0.0,
    BLOCK_MOBSPAWNER: 5,
    BLOCK_CHEST: 2.5,
    BLOCK_REDSTONEWIRE: 0.0,
    BLOCK_DIAMONDORE: 3,
    BLOCK_SOLIDDIAMONDBLOCK: 5,
    BLOCK_CRAFTINGTABLE: 2.5,
    BLOCK_CROPS: 0.0,
    BLOCK_FARMLAND: 0.6,
    BLOCK_FURNACE: 3.5,
    BLOCK_LITFURNACE: 3.5,
    BLOCK_SIGN: 1.0,
    BLOCK_WOODENDOOR: 3,
    BLOCK_LADDER: 0.4,
    BLOCK_RAIL: 0.7,
    BLOCK_WALLSIGN: 1.0,
    BLOCK_LEVER: 0.5,
    BLOCK_STONEFLOORPLATE: 0.5,
    BLOCK_IRONDOOR: 5,
    BLOCK_WOODFLOORPLATE: 0.5,
    BLOCK_REDSTONEORE: 3,
    BLOCK_REDSTONEOREGLOWING: 3,
    BLOCK_REDSTONETORCHOFF: 0.0,
    BLOCK_REDSTONETORCHON: 0.0,
    BLOCK_STONEBUTTON: 0.5,
    BLOCK_SNOW: 0.1,
    BLOCK_ICE: 0.5,
    BLOCK_SNOW: 0.2,
    BLOCK_CACTUS: 0.4,
    BLOCK_CLAY: 0.6,
    BLOCK_REEDS: 0.0,
    BLOCK_JUKEBOX: 2.0,
    BLOCK_FENCE: 2.0,
    BLOCK_PUMPKIN: 1.0,
    BLOCK_BLOODSTONE: 0.4,
    BLOCK_SLOWSAND: 0.5,
    BLOCK_LIGHTSTONE: 0.3,
    BLOCK_NETHERPORTAL: -1,
    BLOCK_GLOWINGPUMPKIN: 1.0
}

MATERIAL_ROCK = frozenset([
    BLOCK_COBBLESTONE,
    BLOCK_BEDROCK,
    BLOCK_REDBRICKTILE,
    BLOCK_MOSSCOVEREDCOBBLESTONE,
    BLOCK_REDSTONEORE,
    BLOCK_REDSTONEOREGLOWING,
    BLOCK_WOODFLOORPLATE,
    BLOCK_STONEFLOORPLATE,
    BLOCK_STONEBUTTON
])

MATERIAL_IRON = frozenset([
    BLOCK_IRONDOOR,
    BLOCK_GOLDORE,
    BLOCK_IRONORE,
    BLOCK_SOLIDIRONBLOCK,
    BLOCK_SOLIDDIAMONDBLOCK,
])


ITEMS = set()
ITEMS_NAMES = {}

#items
for name, id in items.items.names.iteritems():
    varName = "ITEM_"+re.sub(r"[\s\(\)]", "", name).upper()
    globals()[varName] = id
    ITEMS.add(id)
    ITEMS_NAMES[id] = name

ITEMS_TOOLLEVEL = {
    ITEM_WOODSWORD: 0,
    ITEM_WOODSHOVEL: 0,
    ITEM_WOODPICKAXE: 0,
    ITEM_WOODAXE: 0,
    ITEM_WOODHOE: 0,
    
    ITEM_GOLDSWORD: 0,
    ITEM_GOLDSHOVEL: 0,
    ITEM_GOLDPICKAXE: 0,
    ITEM_GOLDAXE: 0,
    ITEM_GOLDHOE: 0,
    
    ITEM_STONESWORD: 1,
    ITEM_STONESHOVEL: 1,
    ITEM_STONEPICKAXE: 1,
    ITEM_STONEAXE: 1,
    ITEM_STONEHOE: 1,
    
    ITEM_IRONSWORD: 2,
    ITEM_IRONSHOVEL: 2,
    ITEM_IRONPICKAXE: 2,
    ITEM_IRONAXE: 2,
    ITEM_IRONHOE: 2,
    
    ITEM_DIAMONDSWORD: 3,
    ITEM_DIAMONDSHOVEL: 3,
    ITEM_DIAMONDPICKAXE: 3,
    ITEM_DIAMONDAXE: 3,
    ITEM_DIAMONDHOE: 3
}

ITEMS_TOOLS = frozenset(ITEMS_TOOLLEVEL.iterkeys())

ITEMS_SWORD = frozenset([
    ITEM_WOODSWORD,
    ITEM_GOLDSWORD,
    ITEM_STONESWORD,
    ITEM_IRONSWORD,
    ITEM_DIAMONDSWORD
])

ITEMS_SHOVEL = frozenset([
    ITEM_WOODSHOVEL,
    ITEM_GOLDSHOVEL,
    ITEM_STONESHOVEL,
    ITEM_IRONSHOVEL,
    ITEM_DIAMONDSHOVEL
])

ITEMS_PICKAXE = frozenset([
    ITEM_WOODPICKAXE,
    ITEM_GOLDPICKAXE,
    ITEM_STONEPICKAXE,
    ITEM_IRONPICKAXE,
    ITEM_DIAMONDPICKAXE
])

ITEMS_AXE = frozenset([
    ITEM_WOODAXE,
    ITEM_GOLDAXE,
    ITEM_STONEAXE,
    ITEM_IRONAXE,
    ITEM_DIAMONDAXE
])

BLOCKITEM_NAMES = dict(BLOCKS_NAMES.items()+ITEMS_NAMES.items())


OBJECT_BOAT = 1
OBJECT_MINECART = 10
OBJECT_STORAGECART = 11
OBJECT_POWEREDCART = 12
OBJECT_ACTIVATEDTNT = 50
OBJECT_ARROW = 60
OBJECT_THROWNSNOWBALL = 61
OBJECT_THROWNEGG = 62
OBJECT_FALLINGSAND = 70
OBJECT_FALLINGGRAVEL = 71
OBJECT_FISHINGFLOAT = 90

INVENTORYTYPE_CHEST = 0
INVENTORYTYPE_WORKBENCH = 1
INVENTORYTYPE_FURNACE = 2