from format import *

#network packets
PACKET_KEEPALIVE = 0x00
PACKET_LOGIN = 0x01
PACKET_HANDSHAKE = 0x02
PACKET_CHAT = 0x03
PACKET_UPDATETIME = 0x04
PACKET_ENTITYEQUIPMENT = 0x05
PACKET_SPAWNPOSITION = 0x06
PACKET_USEENTITY = 0x07
PACKET_PLAYERHEALTH = 0x08
PACKET_RESPAWN = 0x09
PACKET_PLAYERONGROUND = 0x0A
PACKET_PLAYERPOSITION = 0x0B
PACKET_PLAYERLOOK = 0x0C
PACKET_PLAYERPOSITIONLOOK = 0x0D
PACKET_PLAYERBLOCKDIG = 0x0E
PACKET_PLAYERBLOCKPLACE = 0x0F
PACKET_ITEMSWITCH = 0x10
PACKET_ADDINVENTORY = 0x11
PACKET_ANIMATION = 0x12
PACKET_ENTITYACTION = 0x13
PACKET_NAMEDENTITYSPAWN = 0x14
PACKET_PICKUPSPAWN = 0x15
PACKET_COLLECTITEM = 0x16
PACKET_ADDOBJECT = 0x17
PACKET_MOBSPAWN = 0x18
PACKET_ENTITYPAINTING = 0x19
PACKET_UNK1 = 0x1B
PACKET_ENTITYVELOCITY = 0x1C
PACKET_DESTROYENTITY = 0x1D
PACKET_ENTITY = 0x1E
PACKET_ENTITYMOVE = 0x1F
PACKET_ENTITYLOOK = 0x20
PACKET_ENTITYMOVELOOK = 0x21
PACKET_ENTITYTELEPORT = 0x22
PACKET_ENTITYSTATUS = 0x26
PACKET_ATTACHENTITY = 0x27
PACKET_ENTITYMETADATA = 0x28
PACKET_PRECHUNK = 0x32
PACKET_CHUNK = 0x33
PACKET_MULTIBLOCKCHANGE = 0x34
PACKET_BLOCKCHANGE = 0x35
PACKET_PLAYNOTEBLOCK = 0x36
PACKET_EXPLOSION = 0x3C
PACKET_WINDOWOPEN = 0x64
PACKET_WINDOWCLOSE = 0x65
PACKET_WINDOWCLICK = 0x66
PACKET_SETSLOT = 0x67
PACKET_WINDOWITEMS = 0x68
PACKET_TRANSACTION = 0x6A
PACKET_UPDATESIGN = 0x82
PACKET_STATISTIC = 0xC8
PACKET_DISCONNECT = 0xFF
        
PACKET_FORMATS = {
    PACKET_KEEPALIVE: Format(""),
    PACKET_LOGIN: Format("iSqb"),
    PACKET_HANDSHAKE: Format("S"),
    PACKET_CHAT: Format("S"),
    PACKET_UPDATETIME: Format("q"),
    PACKET_ENTITYEQUIPMENT: Format("ihhh"),
    PACKET_SPAWNPOSITION: Format("iii"),
    PACKET_USEENTITY: Format("iib"),
    PACKET_PLAYERHEALTH: Format("h"),
    PACKET_RESPAWN: Format(""),
    PACKET_PLAYERONGROUND: Format("b"),
    PACKET_PLAYERPOSITION: Format("ddddb"),
    PACKET_PLAYERLOOK: Format("ffb"),
    PACKET_PLAYERPOSITIONLOOK: Format("ddddffb"),
    PACKET_PLAYERBLOCKDIG: Format("bibib"),
    PACKET_PLAYERBLOCKPLACE: BlockPlaceFormat(),
    PACKET_ITEMSWITCH: Format("h"),
    PACKET_ADDINVENTORY: Format("hbh"),
    PACKET_ANIMATION: Format("ib"),
    PACKET_ENTITYACTION: Format("ib"),
    PACKET_NAMEDENTITYSPAWN: Format("iSiiibbh"),
    PACKET_PICKUPSPAWN: Format("ihbhiiibbb"),
    PACKET_COLLECTITEM: Format("ii"),
    PACKET_ADDOBJECT: Format("ibiii"),
    PACKET_MOBSPAWN: Format("ibiiibbM"),
    PACKET_ENTITYPAINTING: Format("iSiiii"),
    PACKET_UNK1: Format("ffffbb"),
    PACKET_ENTITYVELOCITY: Format("ihhh"),
    PACKET_DESTROYENTITY: Format("i"),
    PACKET_ENTITY: Format("i"),
    PACKET_ENTITYMOVE: Format("ibbb"),
    PACKET_ENTITYLOOK: Format("ibb"),
    PACKET_ENTITYMOVELOOK: Format("ibbbbb"),
    PACKET_ENTITYTELEPORT: Format("iiiibb"),
    PACKET_ENTITYSTATUS: Format("ib"),
    PACKET_ATTACHENTITY: Format("ii"),
    PACKET_ENTITYMETADATA: Format("iM"),
    PACKET_PRECHUNK: Format("iib"),
    PACKET_CHUNK: ChunkFormat(),
    PACKET_MULTIBLOCKCHANGE: MultiBlockChangeFormat(),
    PACKET_BLOCKCHANGE: Format("ibibb"),
    PACKET_PLAYNOTEBLOCK: Format("ihibb"),
    PACKET_WINDOWOPEN: Format("bbSb"),
    PACKET_WINDOWCLOSE: Format("b"),
    PACKET_WINDOWCLICK: WindowClickFormat(),
    PACKET_WINDOWITEMS: WindowItemsFormat(),
    PACKET_TRANSACTION: Format("bhb"),
    PACKET_EXPLOSION: ExplosionFormat(),
    PACKET_SETSLOT: SetSlotFormat(),
    PACKET_UPDATESIGN: Format("ihiSSSS"),
    PACKET_STATISTIC: Format("ib"),
    PACKET_DISCONNECT: Format("S")
}
